# Generated by Django 5.2.17 on 2026-09-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="integrationticket",
            name="grant_version",
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="user",
            name="grant_version",
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
