# Generated by Django 5.2.17 on 2026-09-21 09:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_modulecheck_operationalissue_audit_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='服务商编码')),
                ('name', models.CharField(max_length=100, verbose_name='服务商名称')),
                ('protocol', models.CharField(choices=[('openai_chat', 'OpenAI Chat 兼容接口')], default='openai_chat', help_text='仅支持 OpenAI Chat 兼容接口，不代表支持所有厂商的原生协议。', max_length=32, verbose_name='接口协议')),
                ('base_url', models.URLField(help_text='使用规范 HTTPS 地址；网络访问允许名单由独立 FastAPI 服务管理。', max_length=500, verbose_name='接口基础地址')),
                ('api_key_env', models.CharField(help_text='仅填写独立 FastAPI 服务环境中的变量名，不是门户进程环境。Key 不入库，请勿填写明文密钥。', max_length=100, validators=[django.core.validators.RegexValidator('^PORTAL_MODEL_KEY_[A-Z0-9_]+$', '请输入 PORTAL_MODEL_KEY_ 开头的大写环境变量名。')], verbose_name='密钥环境变量名')),
                ('enabled', models.BooleanField(default=False, verbose_name='启用')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '模型服务商',
                'verbose_name_plural': '模型服务商',
                'indexes': [],
                'constraints': [],
            },
        ),
        migrations.CreateModel(
            name='GatewayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.provider', verbose_name='模型服务商')),
                ('model_name', models.CharField(max_length=200, verbose_name='远程模型标识')),
                ('supports_text', models.BooleanField(default=True, verbose_name='支持文本')),
                ('enabled', models.BooleanField(default=False, verbose_name='启用')),
                ('timeout_seconds', models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='超时秒数')),
                ('max_output_tokens', models.PositiveIntegerField(default=1024, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8192)], verbose_name='最大输出令牌数')),
                ('token_parameter', models.CharField(choices=[('max_tokens', 'max_tokens'), ('max_completion_tokens', 'max_completion_tokens')], default='max_tokens', max_length=32, verbose_name='令牌限制参数')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '网关模型',
                'verbose_name_plural': '网关模型',
                'indexes': [],
                'constraints': [],
            },
        ),
        migrations.CreateModel(
            name='ModelRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='路由编码')),
                ('name', models.CharField(max_length=100, verbose_name='路由名称')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.module', verbose_name='业务模块')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.gatewaymodel', verbose_name='网关模型')),
                ('enabled', models.BooleanField(default=False, verbose_name='启用')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '业务模型路由',
                'verbose_name_plural': '业务模型路由',
                'indexes': [],
                'constraints': [],
            },
        ),
        migrations.CreateModel(
            name='ModelCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='调用时间')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.modelroute', verbose_name='业务模型路由')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.gatewaymodel', verbose_name='网关模型')),
                ('purpose', models.CharField(choices=[('test', '连接测试'), ('business', '业务调用')], max_length=16, verbose_name='调用用途')),
                ('status', models.CharField(max_length=32, verbose_name='调用状态')),
                ('duration_ms', models.PositiveIntegerField(verbose_name='耗时（毫秒）')),
                ('prompt_tokens', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='输入令牌数')),
                ('completion_tokens', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='输出令牌数')),
            ],
            options={
                'verbose_name': '模型调用日志',
                'verbose_name_plural': '模型调用日志',
                'ordering': ['-created_at', '-id'],
                'indexes': [],
                'constraints': [],
            },
        ),
    ]
