# Generated by Django 5.2.17 on 2026-09-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0009_probation_revision_and_assistant"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="documentrevision",
            name="product_revision_kind_ver_uq",
        ),
        migrations.AddField(
            model_name="documentartifact",
            name="family",
            field=models.CharField(default="technical-solution", max_length=32),
        ),
        migrations.AddField(
            model_name="documentrevision",
            name="family",
            field=models.CharField(default="technical-solution", max_length=32),
        ),
        migrations.AlterField(
            model_name="documentrevision",
            name="kind",
            field=models.CharField(
                choices=[
                    ("input", "输入"),
                    ("blueprint", "蓝图"),
                    ("chapter", "章节"),
                    ("review", "审查"),
                    ("report", "报告内容"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="documentrevision",
            constraint=models.UniqueConstraint(
                fields=("task", "kind", "family", "version"),
                name="product_revision_family_ver_uq",
            ),
        ),
    ]
