# Generated by Django 5.2.17 on 2026-09-26 04:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0011_product_version_lineage"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecruitmentRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position_name", models.CharField(blank=True, max_length=200)),
                ("headcount", models.PositiveIntegerField(blank=True, null=True)),
                ("responsibilities", models.TextField(blank=True)),
                ("required_requirements", models.TextField(blank=True)),
                ("preferred_requirements", models.TextField(blank=True)),
                ("education_requirement", models.CharField(blank=True, max_length=200)),
                (
                    "experience_requirement",
                    models.CharField(blank=True, max_length=200),
                ),
                ("skill_requirements", models.JSONField(default=list)),
                ("work_location", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                ("input_version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recruitment_requests_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recruitment_requests_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("headcount__isnull", True),
                            ("headcount__gt", 0),
                            _connector="OR",
                        ),
                        name="hr_req_headcount_gt0_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("input_version__gt", 0)),
                        name="hr_req_input_version_gt0_ck",
                    ),
                ],
            },
        ),
    ]
