# Generated by Django 5.2.17 on 2026-09-26 04:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0012_hr_recruitment_request"),
    ]

    operations = [
        migrations.CreateModel(
            name="JDVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("input_version", models.PositiveIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[("draft", "草稿"), ("confirmed", "已确认")],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("source", models.CharField(default="skill", max_length=16)),
                ("body", models.TextField()),
                ("channel", models.CharField(default="general", max_length=20)),
                ("custom_label", models.CharField(blank=True, max_length=100)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="jd_versions_confirmed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="jd_versions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="portal.jdversion",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jd_versions",
                        to="portal.recruitmentrequest",
                    ),
                ),
                (
                    "source_jd",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="channel_versions",
                        to="portal.jdversion",
                    ),
                ),
            ],
            options={
                "ordering": ["version"],
            },
        ),
        migrations.AddField(
            model_name="recruitmentrequest",
            name="current_jd",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_for_requests",
                to="portal.jdversion",
            ),
        ),
        migrations.AddField(
            model_name="recruitmentrequest",
            name="official_jd",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="official_for_requests",
                to="portal.jdversion",
            ),
        ),
        migrations.AddConstraint(
            model_name="jdversion",
            constraint=models.UniqueConstraint(
                fields=("request", "version"), name="hr_jd_version_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="jdversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gt", 0)), name="hr_jd_version_gt0_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="jdversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("input_version__gt", 0)),
                name="hr_jd_input_version_gt0_ck",
            ),
        ),
    ]
