# Generated by Django 5.2.17 on 2026-09-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0013_hr_jd_versions"),
    ]

    operations = [
        migrations.AddField(
            model_name="gatewaymodel",
            name="supports_vision",
            field=models.BooleanField(default=False, verbose_name="支持图片输入"),
        ),
    ]
