# Generated by Django 5.2.17 on 2026-09-26 07:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0014_model_vision_capability"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResumeScreeningBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=128)),
                ("input_version", models.PositiveIntegerField()),
                ("requirements", models.JSONField(default=dict)),
                ("status", models.CharField(default="pending", max_length=24)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="screening_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "jd_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="screening_batches",
                        to="portal.jdversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResumeArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file_id", models.CharField(max_length=36)),
                ("filename", models.CharField(max_length=200)),
                ("sha256", models.CharField(max_length=64)),
                ("size", models.PositiveIntegerField()),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "processing_status",
                    models.CharField(db_index=True, default="pending", max_length=24),
                ),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("extracted_text", models.TextField(blank=True)),
                ("extraction", models.JSONField(default=dict)),
                ("profile", models.JSONField(default=dict)),
                ("match", models.JSONField(default=dict)),
                (
                    "cache_key",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("fence", models.PositiveIntegerField(default=0)),
                ("lease_until", models.DateTimeField(blank=True, null=True)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="portal.resumescreeningbatch",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="resumescreeningbatch",
            constraint=models.UniqueConstraint(
                fields=("created_by", "idempotency_key"), name="hr_batch_owner_key_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="resumeartifact",
            constraint=models.UniqueConstraint(
                fields=("batch", "sha256"), name="hr_batch_resume_hash_uq"
            ),
        ),
    ]
