# Generated by Django 5.2.17 on 2026-09-28 01:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0023_hr_model_selection"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenderConsumerHeartbeat",
            fields=[
                (
                    "slot",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("updated_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="TenderFetchRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("QUEUED", "排队"),
                            ("RUNNING", "执行中"),
                            ("SUCCESS", "成功"),
                            ("BLOCKED", "来源阻塞"),
                            ("FAILED", "失败"),
                            ("WAITING_RETRY", "等待重试"),
                            ("SKIPPED", "跳过（已有执行中批次）"),
                        ],
                        default="QUEUED",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "fence",
                    models.PositiveIntegerField(default=0, verbose_name="租约栅栏"),
                ),
                (
                    "lease_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="租约到期"
                    ),
                ),
                (
                    "attempt_count",
                    models.PositiveIntegerField(default=0, verbose_name="尝试次数"),
                ),
                (
                    "version",
                    models.PositiveBigIntegerField(default=1, verbose_name="版本"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "error_code",
                    models.CharField(blank=True, max_length=80, verbose_name="错误码"),
                ),
                (
                    "error_detail",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="错误说明"
                    ),
                ),
                (
                    "stats",
                    models.JSONField(blank=True, default=dict, verbose_name="统计"),
                ),
                (
                    "checkpoint",
                    models.JSONField(blank=True, default=dict, verbose_name="检查点"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TenderNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_notice_id",
                    models.CharField(max_length=200, verbose_name="来源公告标识"),
                ),
                (
                    "canonical_key",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="稳定聚合键"
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="标题")),
                (
                    "notice_type",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="公告类型"
                    ),
                ),
                (
                    "original_url",
                    models.URLField(max_length=1000, verbose_name="原始链接"),
                ),
                (
                    "publish_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="发布时间"
                    ),
                ),
                ("publish_date", models.DateField(blank=True, null=True)),
                (
                    "publish_precision",
                    models.CharField(default="unknown", max_length=10),
                ),
                ("first_seen_at", models.DateTimeField(verbose_name="首次发现")),
                ("last_seen_at", models.DateTimeField(verbose_name="最近发现")),
                (
                    "current_version",
                    models.PositiveIntegerField(default=0, verbose_name="当前版本号"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-last_seen_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TenderSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=120, verbose_name="名称")),
                (
                    "base_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="站点入口"
                    ),
                ),
                (
                    "adapter_code",
                    models.SlugField(max_length=60, verbose_name="适配器标识"),
                ),
                ("enabled", models.BooleanField(default=False, verbose_name="启用")),
                (
                    "fetch_policy",
                    models.JSONField(blank=True, default=dict, verbose_name="抓取策略"),
                ),
                (
                    "health_state",
                    models.CharField(
                        choices=[
                            ("unknown", "未检测"),
                            ("ok", "正常"),
                            ("degraded", "降级"),
                            ("blocked", "被阻塞"),
                            ("error", "异常"),
                        ],
                        default="unknown",
                        max_length=20,
                        verbose_name="健康状态",
                    ),
                ),
                (
                    "health_detail",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="健康说明"
                    ),
                ),
                (
                    "consecutive_failures",
                    models.PositiveIntegerField(default=0, verbose_name="连续失败次数"),
                ),
                (
                    "last_success_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最近成功"
                    ),
                ),
                (
                    "last_failure_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最近失败"
                    ),
                ),
                ("initial_coverage_complete", models.BooleanField(default=False)),
                ("trusted_checkpoint", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="TenderOpportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opportunity_key",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="聚合键"
                    ),
                ),
                (
                    "project_name",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="项目名称"
                    ),
                ),
                (
                    "project_code",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="项目编号"
                    ),
                ),
                (
                    "purchaser",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="采购单位"
                    ),
                ),
                (
                    "agency",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="代理机构"
                    ),
                ),
                (
                    "region",
                    models.CharField(blank=True, max_length=120, verbose_name="地区"),
                ),
                (
                    "notice_type",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="公告类型"
                    ),
                ),
                (
                    "procurement_method",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="采购方式"
                    ),
                ),
                (
                    "budget_amount_yuan",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="预算(元)",
                    ),
                ),
                (
                    "budget_cap_yuan",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="最高限价(元)",
                    ),
                ),
                (
                    "budget_raw",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="预算原文"
                    ),
                ),
                (
                    "publish_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="发布时间"
                    ),
                ),
                ("publish_date", models.DateField(blank=True, null=True)),
                (
                    "publish_precision",
                    models.CharField(default="unknown", max_length=10),
                ),
                (
                    "bid_deadline",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="投标截止"
                    ),
                ),
                (
                    "bid_open_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开标时间"
                    ),
                ),
                (
                    "signup_time_text",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="报名时间(原文)"
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=120, verbose_name="联系人"),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="联系方式"
                    ),
                ),
                (
                    "attachment_count",
                    models.PositiveIntegerField(default=0, verbose_name="附件数"),
                ),
                (
                    "attachment_urls",
                    models.JSONField(blank=True, default=list, verbose_name="附件地址"),
                ),
                (
                    "unknown_fields",
                    models.JSONField(
                        blank=True, default=list, verbose_name="未能确定的字段"
                    ),
                ),
                (
                    "possible_match_keys",
                    models.JSONField(
                        blank=True, default=list, verbose_name="可能的跨来源匹配"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "进行中"),
                            ("UPDATED", "有更新"),
                            ("AWARDED", "已中标"),
                            ("CLOSED", "已结束"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "current_version",
                    models.PositiveIntegerField(default=0, verbose_name="当前公告版本"),
                ),
                (
                    "first_seen_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="首次发现"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "primary_notice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opportunities",
                        to="portal.tendernotice",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opportunities",
                        to="portal.tendersource",
                    ),
                ),
            ],
            options={
                "ordering": ["-publish_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TenderRecoveryAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_type", models.CharField(max_length=12)),
                ("target_id", models.CharField(max_length=40)),
                ("reason", models.CharField(max_length=200)),
                ("confirmed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TenderSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=1000, verbose_name="来源地址")),
                ("fetched_at", models.DateTimeField(verbose_name="抓取时间")),
                (
                    "http_status",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="HTTP 状态"
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="内容类型"
                    ),
                ),
                (
                    "storage_path",
                    models.CharField(max_length=500, verbose_name="存储相对路径"),
                ),
                (
                    "content_sha256",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="内容摘要"
                    ),
                ),
                ("byte_size", models.PositiveIntegerField(verbose_name="字节数")),
                (
                    "source_metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="来源元数据"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="snapshots",
                        to="portal.tenderfetchrun",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="portal.tendersource",
                    ),
                ),
            ],
            options={
                "ordering": ["-fetched_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TenderNoticeVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField(verbose_name="版本号")),
                (
                    "content_hash",
                    models.CharField(max_length=64, verbose_name="内容摘要"),
                ),
                (
                    "normalized",
                    models.JSONField(blank=True, default=dict, verbose_name="归一字段"),
                ),
                (
                    "attachments",
                    models.JSONField(blank=True, default=list, verbose_name="附件"),
                ),
                (
                    "change_summary",
                    models.JSONField(
                        blank=True, default=list, verbose_name="相对上一版变化"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="portal.tendernotice",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="superseded_by",
                        to="portal.tendernoticeversion",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="versions",
                        to="portal.tendersnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["-version", "-id"],
            },
        ),
        migrations.AddField(
            model_name="tendernotice",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notices",
                to="portal.tendersource",
            ),
        ),
        migrations.AddField(
            model_name="tenderfetchrun",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="runs",
                to="portal.tendersource",
            ),
        ),
        migrations.CreateModel(
            name="TenderSourceHealthEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("PREFLIGHT_OK", "预检通过"),
                            ("PREFLIGHT_BLOCKED", "预检阻塞"),
                            ("FETCH_FAILED", "抓取失败"),
                            ("RATE_LIMITED", "被限流"),
                            ("DEGRADED", "降级"),
                            ("RECOVERED", "已恢复"),
                        ],
                        max_length=30,
                        verbose_name="事件类型",
                    ),
                ),
                ("occurred_at", models.DateTimeField(verbose_name="发生时间")),
                (
                    "reason_code",
                    models.CharField(blank=True, max_length=80, verbose_name="原因码"),
                ),
                (
                    "detail",
                    models.CharField(blank=True, max_length=500, verbose_name="说明"),
                ),
                (
                    "payload",
                    models.JSONField(blank=True, default=dict, verbose_name="事件载荷"),
                ),
                ("dedupe_key", models.CharField(max_length=255, verbose_name="幂等键")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_events",
                        to="portal.tendersource",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TenderManualRefresh",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "active_slot",
                    models.PositiveSmallIntegerField(default=1, editable=False),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("QUEUED", "等待执行"),
                            ("RUNNING", "执行中"),
                            ("SUCCESS", "完整完成"),
                            ("PARTIAL", "部分更新"),
                            ("INTERRUPTED", "中断"),
                            ("FAILED", "失败"),
                        ],
                        default="QUEUED",
                        max_length=20,
                    ),
                ),
                ("source_codes", models.JSONField(default=list)),
                ("source_plan", models.JSONField(default=dict)),
                ("results", models.JSONField(default=dict)),
                ("fence", models.PositiveIntegerField(default=0)),
                ("lease_until", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("error_detail", models.CharField(blank=True, max_length=500)),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("active_slot", 1)),
                        name="tender_refresh_single_slot",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("state__in", ["QUEUED", "RUNNING"])),
                        fields=("active_slot",),
                        name="tender_one_active_refresh",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TenderOpportunityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("DISCOVERED", "首次发现"),
                            ("NOTICE_UPDATED", "公告更新"),
                            ("DEADLINE_CHANGED", "截止时间变化"),
                            ("DOCUMENT_ADDED", "新增附件"),
                            ("BUDGET_CHANGED", "预算变化"),
                            ("REQUIREMENT_CHANGED", "要求变化"),
                            ("AWARD_PUBLISHED", "中标结果发布"),
                        ],
                        max_length=40,
                        verbose_name="事件类型",
                    ),
                ),
                ("occurred_at", models.DateTimeField(verbose_name="发生时间")),
                (
                    "payload",
                    models.JSONField(blank=True, default=dict, verbose_name="事件载荷"),
                ),
                ("dedupe_key", models.CharField(max_length=255, verbose_name="幂等键")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notice_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="portal.tendernoticeversion",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="portal.tenderopportunity",
                    ),
                ),
            ],
            options={
                "ordering": ["occurred_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["opportunity", "occurred_at"],
                        name="tender_event_opp_time",
                    ),
                    models.Index(
                        fields=["event_type", "-occurred_at"],
                        name="tender_event_type_time",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("opportunity", "dedupe_key"),
                        name="tender_event_dedupe_uniq",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="tendernoticeversion",
            constraint=models.UniqueConstraint(
                fields=("notice", "content_hash"), name="tender_noticever_hash_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="tendernoticeversion",
            constraint=models.UniqueConstraint(
                fields=("notice", "version"), name="tender_noticever_ver_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="tendersnapshot",
            index=models.Index(
                fields=["source", "-fetched_at"], name="tender_snap_src_time"
            ),
        ),
        migrations.AddIndex(
            model_name="tenderopportunity",
            index=models.Index(fields=["-publish_at"], name="tender_opp_publish"),
        ),
        migrations.AddIndex(
            model_name="tenderopportunity",
            index=models.Index(
                fields=["region", "-publish_at"], name="tender_opp_region_time"
            ),
        ),
        migrations.AddIndex(
            model_name="tenderopportunity",
            index=models.Index(fields=["bid_deadline"], name="tender_opp_deadline"),
        ),
        migrations.AddIndex(
            model_name="tenderopportunity",
            index=models.Index(
                fields=["status", "-updated_at"], name="tender_opp_status_time"
            ),
        ),
        migrations.AddIndex(
            model_name="tendernotice",
            index=models.Index(fields=["canonical_key"], name="tender_notice_canon"),
        ),
        migrations.AddConstraint(
            model_name="tendernotice",
            constraint=models.UniqueConstraint(
                fields=("source", "source_notice_id"), name="tender_notice_src_nid_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="tenderfetchrun",
            index=models.Index(
                fields=["state", "created_at"], name="tender_run_state_time"
            ),
        ),
        migrations.AddIndex(
            model_name="tenderfetchrun",
            index=models.Index(
                fields=["source", "-created_at"], name="tender_run_src_time"
            ),
        ),
        migrations.AddConstraint(
            model_name="tenderfetchrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "RUNNING")),
                fields=("source",),
                name="tender_one_running_per_source",
            ),
        ),
        migrations.AddIndex(
            model_name="tendersourcehealthevent",
            index=models.Index(
                fields=["source", "-occurred_at"], name="tender_src_health_time"
            ),
        ),
        migrations.AddIndex(
            model_name="tendersourcehealthevent",
            index=models.Index(
                fields=["event_type", "-occurred_at"], name="tender_src_health_type"
            ),
        ),
        migrations.AddConstraint(
            model_name="tendersourcehealthevent",
            constraint=models.UniqueConstraint(
                fields=("source", "dedupe_key"), name="tender_source_health_dedupe_uniq"
            ),
        ),
    ]
