import django.db.models.deletion
import portal.agent_models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0029_tender_extraction_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department_code',
            field=models.CharField(blank=True, choices=[('product', '产品'), ('hr', '人事'),
                ('finance', '财务'), ('engineering', '工程')], max_length=20, verbose_name='所属部门'),
        ),
        migrations.CreateModel(
            name='AgentConversation',
            fields=[
                ('id', models.UUIDField(default=portal.agent_models.identifier, editable=False, primary_key=True, serialize=False)),
                ('department_code', models.CharField(blank=True, max_length=20)),
                ('root_run_id', models.UUIDField(default=portal.agent_models.identifier, editable=False, unique=True)),
                ('create_key', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentMessage',
            fields=[
                ('id', models.UUIDField(default=portal.agent_models.identifier, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'user'), ('assistant', 'assistant')], max_length=12)),
                ('content', models.TextField()),
                ('attachment_references', models.JSONField(default=list)),
                ('client_request_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.agentconversation')),
            ],
        ),
        migrations.CreateModel(
            name='AgentProject',
            fields=[
                ('id', models.UUIDField(default=portal.agent_models.identifier, editable=False, primary_key=True, serialize=False)),
                ('department_code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='agentconversation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.agentproject'),
        ),
        migrations.CreateModel(
            name='AgentRequirement',
            fields=[
                ('id', models.UUIDField(default=portal.agent_models.identifier, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('source_versions', models.JSONField(default=list)),
                ('source_hash', models.CharField(blank=True, max_length=64)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('user_message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.agentmessage')),
            ],
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.UUIDField(default=portal.agent_models.identifier, editable=False, primary_key=True, serialize=False)),
                ('root_run_id', models.UUIDField(db_index=True)),
                ('native_thread_id', models.CharField(blank=True, max_length=160)),
                ('native_run_id', models.CharField(blank=True, max_length=160)),
                ('state', models.CharField(default='pending', max_length=24)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('policy', models.JSONField(default=dict)),
                ('action_count', models.PositiveIntegerField(default=0)),
                ('model_count', models.PositiveIntegerField(default=0)),
                ('tool_count', models.PositiveIntegerField(default=0)),
                ('launch_count', models.PositiveIntegerField(default=0)),
                ('next_event_seq', models.PositiveBigIntegerField(default=1)),
                ('stop_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.agentconversation')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.agentrun')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.agentrequirement')),
            ],
        ),
        migrations.CreateModel(
            name='AgentRootAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_key', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('model', 'model'), ('tool', 'tool'), ('launch', 'launch')], max_length=12)),
                ('status', models.CharField(default='reserved', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.agentrun')),
            ],
        ),
        migrations.CreateModel(
            name='AgentSkillInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_id', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=80)),
                ('digest', models.CharField(max_length=64)),
                ('enabled', models.BooleanField(default=True)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentWorkTask',
            fields=[
                ('id', models.UUIDField(default=portal.agent_models.identifier, editable=False, primary_key=True, serialize=False)),
                ('department_code', models.CharField(max_length=20)),
                ('goal', models.TextField()),
                ('state', models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('waiting_input', 'waiting_input'), ('waiting_confirmation', 'waiting_confirmation'), ('stopping', 'stopping'), ('completed', 'completed'), ('failed', 'failed'), ('cancelled', 'cancelled'), ('terminated', 'terminated')], default='queued', max_length=24)),
                ('current_requirement_version', models.PositiveIntegerField(default=0)),
                ('result_references', models.JSONField(default=list)),
                ('stop_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.agentconversation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('predecessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.agentworktask')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.agentproject')),
            ],
        ),
        migrations.AddField(
            model_name='agentrun',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.agentworktask'),
        ),
        migrations.AddField(
            model_name='agentrequirement',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.agentworktask'),
        ),
        migrations.AddField(
            model_name='agentmessage',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.agentworktask'),
        ),
        migrations.CreateModel(
            name='AgentEvent',
            fields=[
                ('id', models.UUIDField(default=portal.agent_models.identifier, editable=False, primary_key=True, serialize=False)),
                ('seq', models.PositiveBigIntegerField()),
                ('event_key', models.CharField(max_length=160)),
                ('type', models.CharField(max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.agentrun')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='portal.agentrun')),
                ('work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.agentworktask')),
            ],
            options={
                'ordering': ['seq'],
            },
        ),
        migrations.CreateModel(
            name='AgentBusinessReference',
            fields=[
                ('id', models.UUIDField(default=portal.agent_models.identifier, editable=False, primary_key=True, serialize=False)),
                ('domain_type', models.CharField(max_length=60)),
                ('object_id', models.CharField(max_length=160)),
                ('revision', models.CharField(blank=True, max_length=160)),
                ('digest', models.CharField(blank=True, max_length=64)),
                ('operation_key', models.CharField(max_length=160)),
                ('public_summary', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.agentrequirement')),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.agentrun')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.agentworktask')),
            ],
        ),
        migrations.AddConstraint(
            model_name='agentconversation',
            constraint=models.UniqueConstraint(condition=models.Q(('create_key', ''), _negated=True), fields=('owner', 'create_key'), name='agent_conv_owner_key'),
        ),
        migrations.AddConstraint(
            model_name='agentrootaction',
            constraint=models.UniqueConstraint(fields=('root', 'action_key'), name='agent_root_action_key'),
        ),
        migrations.AddConstraint(
            model_name='agentskillinstallation',
            constraint=models.UniqueConstraint(fields=('owner', 'skill_id'), name='agent_skill_owner_id'),
        ),
        migrations.AddConstraint(
            model_name='agentrequirement',
            constraint=models.UniqueConstraint(fields=('work', 'version'), name='agent_requirement_version'),
        ),
        migrations.AddConstraint(
            model_name='agentmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('client_request_id', ''), _negated=True), fields=('conversation', 'client_request_id'), name='agent_msg_conv_key'),
        ),
        migrations.AddConstraint(
            model_name='agentevent',
            constraint=models.UniqueConstraint(fields=('root', 'seq'), name='agent_event_root_seq'),
        ),
        migrations.AddConstraint(
            model_name='agentevent',
            constraint=models.UniqueConstraint(fields=('root', 'event_key'), name='agent_event_root_key'),
        ),
        migrations.AddConstraint(
            model_name='agentbusinessreference',
            constraint=models.UniqueConstraint(fields=('root', 'operation_key'), name='agent_business_operation'),
        ),
        migrations.AddField(model_name='agentworktask', name='public_summary',
            field=models.CharField(blank=True, max_length=300)),
        migrations.AddField(model_name='modelcalllog', name='root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                related_name='root_model_calls', to='portal.agentrun')),
        migrations.AddField(model_name='modelcalllog', name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                related_name='model_calls', to='portal.agentrun')),
        migrations.AddField(model_name='modelcalllog', name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                to='portal.agentconversation')),
        migrations.AddField(model_name='modelcalllog', name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                to='portal.agentworktask')),
        migrations.AddField(model_name='modelcalllog', name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                to='portal.agentrequirement')),
        migrations.AddField(model_name='modelcalllog', name='physical_call_id',
            field=models.CharField(blank=True, max_length=160, null=True, unique=True)),
        migrations.CreateModel(
            name='AgentAttachment',
            fields=[
                ('id', models.UUIDField(default=portal.agent_models.identifier, editable=False, primary_key=True, serialize=False)),
                ('department_code', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.PositiveBigIntegerField()),
                ('path', models.CharField(max_length=500)),
                ('sha256', models.CharField(max_length=64)),
                ('source_scope', models.CharField(default='private', max_length=20)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(model_name='agentmessage', name='execution_state',
            field=models.CharField(default='pending', max_length=30)),
        migrations.AddField(model_name='agentmessage', name='execution_reason',
            field=models.CharField(blank=True, max_length=100)),
    ]
