import { CenterLink } from "../centers/shared";
import { DocumentSymbol, LoadState, outputNames, ProductIcon, useProductOverview } from "./workbench-shared";

export default function ProductTemplates() {
  const { data, error, reload } = useProductOverview();
  if (!data) return <LoadState error={error} reload={reload}/>;
  return <div className="pd-workspace"><div className="pd-page-title"><div><h2>模板与编制说明</h2><p>统一文档规范，分别核验三类成果；不改变原始项目事实。</p></div></div><div className="pd-output-grid">{(["technical-solution", "feasibility", "presentation"] as const).map(family => <article className="pd-panel pd-template-card" key={family}><DocumentSymbol family={family}/><h3>{outputNames[family]}</h3><p>{family === "technical-solution" ? "建设目标、系统方案、实施计划与边界条件。" : family === "feasibility" ? "必要性、方案比选、实施条件与风险。经济分析需要完整的成本与收益依据。" : "从已批准的技术方案和可研结构化内容派生，保留来源版本。"}</p><span className="pd-badge info">{family === "presentation" ? "PPTX" : "DOCX"}</span></article>)}</div>
    {data.templates.map(template => <section className="pd-panel" key={template.id}><div className="pd-panel-heading"><h3>{template.name}</h3><span className={`pd-badge ${template.approved ? "good" : "warning"}`}>{template.approved ? "母版已签认" : "正式母版待签认"}</span></div><p>{template.description}</p><p className="pd-muted">规则版本：{template.version}</p></section>)}
    <section className="pd-panel"><div className="pd-panel-heading"><h3>准备项目资料</h3><ProductIcon name="upload"/></div><p>当前可上传 {data.capabilities.upload_extensions.join("、")}；单个文件不超过 {(data.capabilities.upload_max_bytes / 1048576).toFixed(0)} MB。CSV 设备清单使用 UTF-8 编码，建议包含“序号、设备名称、数量、单位”。缺项保留并交由人工核对。</p><div className="pd-actions"><a className="button secondary" download="设备清单空白模板.csv" href={`data:text/csv;charset=utf-8,${encodeURIComponent("\uFEFF序号,设备名称,数量,单位\r\n")}`}><ProductIcon name="download"/>下载空白清单</a><CenterLink href="/centers/product/new" className="button primary">创建项目</CenterLink></div></section>
    <section className="pd-panel"><h3>资料解析方式</h3><div className="pd-table-wrap"><table className="pd-table"><thead><tr><th>格式</th><th>提取内容与位置</th><th>需要核对</th></tr></thead><tbody><tr><td>PDF</td><td>文字层、页码；扫描页按需本地 OCR，提供原页预览</td><td>每份最多 100 页、12 个 OCR 页或图片；超出部分明确提示</td></tr><tr><td>Word（DOCX）</td><td>段落、表格、页眉页脚、注释性附注与内嵌位图文字</td><td>修订、合并单元格及图片识别需核对；旧 DOC 请另存为 DOCX</td></tr><tr><td>Excel（XLSX / XLS）</td><td>工作表、单元格范围；明确表头的 XLSX 设备清单</td><td>不执行公式或外部链接；旧 XLS 只读取保存值，不自动确认数量</td></tr><tr><td>图片</td><td>本地中文 OCR、文字框与置信度，保留原图预览</td><td>数字、单位、低置信度文字需核对；不推断图纸含义</td></tr></tbody></table></div><p className="pd-muted">解析原件、人工校正和审核判断分别留存版本；不会因“解析完成”自动批准事实。</p></section>
    <section className="pd-panel"><h3>生成与交付边界</h3><div className="pd-capability-list">{[{ label: "模型与预算授权", enabled: data.capabilities.model_generation }, { label: "授权知识检索", enabled: data.capabilities.retrieval }, { label: "目标 Office 渲染", enabled: data.capabilities.office_preview }, { label: "正式发布许可", enabled: data.capabilities.formal_release }].map(item => <div key={item.label}><strong>{item.label}</strong><span className={`pd-badge ${item.enabled ? "good" : "neutral"}`}>{item.enabled ? "已配置" : "待配置"}</span></div>)}</div><p className="pd-muted">配置状态不等于业务验收。文件生成、内容审核、格式核验和正式批准分别执行。</p></section>
  </div>;
}
