import { useEffect, useState } from "react";
import { CenterLink, Field } from "../centers/shared";
import { artifactDownload, artifactHistoryDownload, artifactPreview, draftDownload, draftHistoryDownload, sourceDownload, type BlueprintPayload, type DocumentTask, type DraftOutput, type TaskHistory } from "./product-api";
import { DocumentSymbol, EmptyState, formatBytes, formatDate, goProduct, outputNames, ProductIcon, projectUrl, stageNames, stateNames, StatusBadge, useUnsavedWarning } from "./workbench-shared";

import ProjectInputPanel from "./ProjectInputPanel";
import SourceMaterials from "./SourceMaterials";
import { SOURCE_ACCEPT, extractionNames, type SourceAction } from "./product-api";

type Action = (endpoint: string, body: object) => Promise<unknown>;
interface Props { task: DocumentTask; outputs: DraftOutput[]; history: TaskHistory | null; outputsError: string; historyError: string; busy: boolean; conflict: boolean; disabled: (action: string) => boolean; onAction: Action; onReload: () => void; onUpload: (file: File) => Promise<unknown>; onSourceAction?: SourceAction }
const tabs = [{ id: "overview", name: "项目概览" }, { id: "blueprint", name: "项目蓝图" }, { id: "outputs", name: "当前成果" }, { id: "sources", name: "输入资料" }, { id: "history", name: "版本记录" }];
const readTab = () => { const tab = new URLSearchParams(window.location.search).get("tab") || "overview"; return tabs.some(item => item.id === tab) ? tab : "overview"; };
const lines = (value: string) => value.split("\n").map(text => text.trim()).filter(Boolean);

export default function ProjectStages(props: Props) {
  const { task, outputs, history, outputsError, historyError, busy, conflict, disabled, onAction, onReload, onUpload, onSourceAction } = props;
  const [tab, setTab] = useState(readTab);
  const [cancelling, setCancelling] = useState(false);
  const [file, setFile] = useState<File | null>(null);
  useEffect(() => { let active = true; const sync = () => queueMicrotask(() => { if (active) setTab(readTab()); }); window.addEventListener("popstate", sync); return () => { active = false; window.removeEventListener("popstate", sync); }; }, []);
  const move = (value: string) => goProduct(projectUrl(task.id, value));
  const running = ["RUNNING", "QUEUED"].includes(task.state);
  const currentFamilies = new Set(outputs.filter(item => item.current).map(item => item.family));
  const steps = [
    { title: "项目资料", done: !!task.input, selected: task.stage === "INTAKE" },
    { title: "生成蓝图", done: !!task.blueprint, selected: task.stage === "BLUEPRINT" && task.state !== "WAITING_REVIEW" },
    { title: "蓝图确认", done: task.blueprint_approved === true, selected: task.stage === "BLUEPRINT" && task.state === "WAITING_REVIEW" },
    { title: "技术方案", done: currentFamilies.has("technical-solution"), selected: ["WRITING", "CONTENT_CHECK", "RENDER"].includes(task.stage) },
    { title: "可研报告", done: currentFamilies.has("feasibility"), selected: false },
    { title: "汇报 PPT", done: currentFamilies.has("presentation"), selected: task.pending_action === "presentation" },
    { title: "审核归档", done: task.state === "COMPLETED", selected: task.stage === "FINAL_REVIEW" && task.state !== "COMPLETED" },
  ];
  return <div className="pd-workspace pd-project-detail">
    <div className="pd-page-title"><div><CenterLink href="/centers/product/projects" className="pd-back-link">← 所有项目</CenterLink><h2>{task.title} <StatusBadge task={task}/></h2><p>{stageNames[task.stage] || "阶段待确认"} · 项目版本 v{task.version} · 更新于 {formatDate(task.updated_at)}</p></div><div className="pd-actions"><button className="button secondary" disabled={busy} onClick={onReload}>刷新状态</button>{!disabled("cancel") && <button className="text-button pd-danger" onClick={() => setCancelling(true)}>取消任务</button>}</div></div>
    {conflict && <div className="pd-feedback" role="alert">版本或前置条件发生变化。未保存的编辑已保留，请刷新后核对；不会自动覆盖服务端内容。</div>}
    {cancelling && <section role="alertdialog" aria-label="确认取消任务" className="pd-feedback"><h3>确认取消当前任务？</h3><p>取消后不能继续编辑这个任务。已上传资料和历史成果仍保留，不会删除。</p><div className="pd-actions"><button className="button secondary" onClick={() => setCancelling(false)}>继续处理</button><button className="button primary" disabled={busy || disabled("cancel")} onClick={async () => { if (await onAction("cancel/", {})) setCancelling(false); }}>确认取消</button></div></section>}
    <ol className="pd-project-steps" aria-label="项目流程">{steps.map((step, index) => <li key={step.title} className={step.done ? "done" : step.selected ? "current" : ""} aria-current={step.selected && !step.done ? "step" : undefined}><span>{step.done ? <ProductIcon name="check"/> : index + 1}</span><strong>{step.title}</strong></li>)}</ol>
    <nav className="pd-detail-tabs" aria-label="项目详情栏目">{tabs.map(item => <button type="button" key={item.id} className={tab === item.id ? "active" : ""} aria-current={tab === item.id ? "page" : undefined} onClick={() => move(item.id)}>{item.name}{item.id === "sources" && <small>{task.sources.length}</small>}</button>)}</nav>
    {tab === "overview" && <>
      <section className="pd-panel pd-stage-status"><span className={`pd-stage-symbol ${running ? "blue" : task.state === "COMPLETED" ? "green" : "orange"}`}><ProductIcon name={running ? "settings" : task.state === "COMPLETED" ? "check" : "clock"}/></span><div><h3>{task.state === "WAITING_REVIEW" && task.stage === "BLUEPRINT" ? "项目蓝图已就绪，等待人工确认" : stateNames[task.state] || "项目状态待确认"}</h3><p>{running ? "任务由后台服务处理，离开页面不会取消。页面按服务端状态更新。" : task.blueprint_approved ? "蓝图已确认，后续成果共享这一版本的项目依据。" : "先整理项目资料，再核对目标、建设范围和蓝图条件。"}</p>{running && <div className="pd-indeterminate" role="progressbar" aria-label={task.state === "QUEUED" ? "等待后台执行" : "后台正在处理"}><span/></div>}</div><div className="pd-actions">{!disabled("retry") && <button className="button secondary" onClick={() => void onAction("retry/", {})}>重试任务</button>}<button className="button primary" onClick={() => move(task.blueprint ? "blueprint" : "sources")}>{task.blueprint ? "查看项目蓝图" : "整理项目资料"}<ProductIcon name="arrow"/></button></div></section>
      {task.error_code && <div className="pd-feedback" role="alert"><strong>当前任务需要处理</strong><p>{task.error_code === "model_authorization_required" ? "尚未取得模型调用与资料外发授权。项目已保留，可以先完善资料与人工蓝图。" : task.error_code === "revision_requested" ? "审核人已退回修改，请查看审核记录并修订。" : `执行未完成（${task.error_code}），请核对资料或联系负责人。`}</p></div>}
      <div className="pd-detail-grid"><section className="pd-panel"><div className="pd-panel-heading"><h3>项目基本信息</h3><button className="text-button" onClick={() => move("sources")}>查看资料 ›</button></div><dl className="pd-description"><dt>建设目标</dt><dd>{task.input?.requirements || "尚未填写"}</dd><dt>项目背景</dt><dd>{task.input?.background || "尚未填写"}</dd><dt>约束条件</dt><dd>{task.input?.conditions.length ? task.input.conditions.map((text, i) => <p key={i}>{text}</p>) : "暂无已记录条件"}</dd></dl></section><section className="pd-panel"><div className="pd-panel-heading"><h3>成果概况</h3><button className="text-button" onClick={() => move("outputs")}>查看成果 ›</button></div>{outputsError ? <p role="alert">{outputsError}</p> : <div className="pd-summary-outputs">{(["technical-solution", "feasibility", "presentation"] as const).map(family => { const item = outputs.filter(value => value.family === family && value.current).at(-1); return <div key={family}><DocumentSymbol family={family}/><span><strong>{outputNames[family]}</strong><small>{item ? `v${item.version} · ${item.approved ? "已批准" : "待审核稿"}` : "尚无当前成果"}</small></span></div>; })}</div>}<p className="pd-muted">成果生成不等于正式批准。三类成果分别核验，历史版本不覆盖。</p></section></div>
      <section className="pd-panel"><div className="pd-panel-heading"><h3>下一步操作</h3><span className="pd-muted">按当前授权与任务状态开放</span></div><div className="pd-actions"><button className="button primary" disabled={disabled("queue_blueprint")} onClick={() => void onAction("queue/", { action: "blueprint" })}>生成项目蓝图</button><button className="button secondary" disabled={disabled("save_blueprint")} onClick={() => move("blueprint")}>人工编制蓝图</button><button className="button secondary" disabled={disabled("queue_write")} onClick={() => void onAction("queue/", { action: "write" })}>生成正文</button><button className="button secondary" onClick={() => move("outputs")}>编制与审核成果</button></div><BlockerNotes task={task}/></section>
    </>}
    {tab === "blueprint" && <BlueprintPanel task={task} disabled={disabled} busy={busy} onAction={onAction}/>}
    {tab === "outputs" && <><div className="pd-panel-heading"><div><h3>当前成果</h3><p className="pd-muted">仅展示与当前资料、蓝图及内容版本一致的文件。</p></div><button className="text-button" onClick={() => move("history")}>历史版本 ›</button></div>{outputsError ? <div role="alert" className="pd-feedback">{outputsError}</div> : <div className="pd-output-grid">{(["technical-solution", "feasibility", "presentation"] as const).map(family => {
      const output = outputs.filter(item => item.family === family && item.current).at(-1);
      const artifact = output && task.artifacts.find(item => item.id === output.id);
      return <article className="pd-panel pd-artifact" key={family}><div className="pd-artifact-head"><DocumentSymbol family={family}/><div><h3>{outputNames[family]}</h3><small>{family === "presentation" ? "PowerPoint · PPTX" : "Word · DOCX"}</small></div></div>{output ? <><span className={`pd-badge ${output.approved ? "good" : "warning"}`}>{output.approved ? "已批准" : "待审核稿"} · v{output.version}</span><p className="pd-muted">{output.content_version ? `来源内容 v${output.content_version} · ${output.content_approved ? "内容已审" : "内容待审"}` : "保留结构化内容来源"}</p><div className="pd-actions"><a className="button primary" href={family === "technical-solution" ? artifactDownload(output.id) : draftDownload(output.id)}><ProductIcon name="download"/>下载文件</a>{artifact?.render_evidence?.pages.length ? <a className="button secondary" href={artifactPreview(artifact.id, 1)} target="_blank" rel="noreferrer">预览第 1 页</a> : <span className="pd-muted">暂无 Office 预览证据</span>}</div></> : <><span className="pd-badge neutral">尚未生成</span><p>完成当前阶段和必要审核后生成。历史成果请在版本记录中查看。</p></>}</article>;
    })}</div>}
      <section className="pd-panel"><h3>文档编制与内容审核</h3><div className="pd-actions"><button className="button primary" disabled={disabled("queue_three_drafts")} onClick={() => void onAction("queue/", { action: "three_drafts" })}>生成技术方案与可研 Word</button><button className="button secondary" disabled={disabled("queue_presentation")} onClick={() => void onAction("queue/", { action: "presentation" })}>从已审内容生成 PPT</button><button className="button secondary" disabled={disabled("queue_candidate")} onClick={() => void onAction("queue/", { action: "candidate" })}>生成正式候选与 Office 预览</button></div><p className="pd-muted">Word 需要两份完整正文；PPT 需要已批准的技术方案和可研内容。正式候选还需模板与 Office 环境许可。</p><BlockerNotes task={task}/><CenterLink href={`/centers/product/documents?task=${encodeURIComponent(task.id)}`} className="pd-quiet-link">进入专业核验：章节编辑、内容批准、逐页核验与正式批准 ›</CenterLink></section>
    </>}
    {tab === "sources" && <><ProjectInputPanel task={task} disabled={disabled} onAction={onAction}/><section className="pd-panel"><div className="pd-panel-heading"><h3>原始资料</h3><span className="pd-muted">{task.sources.length} 份资料</span></div>{task.sources.length ? <ul className="pd-upload-list">{task.sources.map(source => <li key={source.id}><ProductIcon name="file"/><div><strong>{source.original_name}</strong><small>{source.parsed ? `${extractionNames[source.parsed.status]} · ` : ""}{formatBytes(source.size)} · {formatDate(source.created_at)}{source.warnings?.length ? ` · ${source.warnings.length} 项待核对` : ""}</small></div><a className="button secondary" href={sourceDownload(source.id)}>下载原文件</a></li>)}</ul> : <EmptyState title="尚未上传附件" detail="可以先填写建设目标，也可以补充设备清单和背景资料。"/>}<div className="pd-source-upload"><label htmlFor="project-more-file">补充资料</label><input id="project-more-file" type="file" accept={SOURCE_ACCEPT} disabled={disabled("add_source")} onChange={event => setFile(event.target.files?.[0] || null)}/><button className="button primary" disabled={disabled("add_source") || !file} onClick={async () => { if (file && await onUpload(file)) setFile(null); }}>{busy ? "正在上传并解析…" : "上传并保存"}</button></div><p className="pd-muted">补充资料会形成新的输入版本，相关蓝图和成果需重新核对。上传不会覆盖原始文件。</p></section>
      <SourceMaterials task={task} busy={busy} onSourceAction={onSourceAction} onAction={onAction} disabled={disabled}/>
      <section className="pd-panel"><div className="pd-panel-heading"><h3>设备清单事实</h3><span className="pd-badge neutral">{task.input?.items.length || 0} 行</span></div>{task.input?.items.length ? <div className="pd-table-wrap"><table className="pd-table"><thead><tr><th>原行号</th><th>设备名称</th><th>数量</th><th>单位</th><th>来源位置</th></tr></thead><tbody>{task.input.items.map((item, i) => <tr key={i}><td>{item.row_id || "未提供"}</td><td>{item.name || "名称缺失"}</td><td>{item.quantity === "" ? "未提供" : item.quantity}</td><td>{item.unit || "未提供"}</td><td>{task.sources.find(source => source.id === item.source_id)?.original_name || "人工录入"}{item.source_location && <small>{[item.source_location.sheet, item.source_location.part, item.source_location.range, item.source_location.table ? `表 ${item.source_location.table}` : "", item.source_location.row ? `第 ${item.source_location.row} 行` : ""].filter(Boolean).join(" · ")}</small>}</td></tr>)}</tbody></table></div> : <p className="pd-muted">尚未录入设备清单，可上传清单或在项目底稿中补充。</p>}{task.input_issues.length > 0 && <p className="pd-feedback">有 {task.input_issues.length} 项输入问题需要审核人结合来源核对。</p>}<CenterLink className="pd-quiet-link" href={`/centers/product/documents?task=${encodeURIComponent(task.id)}`}>进入专业工作台核对输入问题 ›</CenterLink></section></>}
    {tab === "history" && <><section className="pd-panel"><div className="pd-panel-heading"><h3>成果历史版本</h3><span className="pd-muted">保留旧版，不覆盖</span></div>{outputsError ? <p role="alert">{outputsError}</p> : outputs.length ? <div className="pd-table-wrap"><table className="pd-table"><thead><tr><th>成果</th><th>版本</th><th>状态</th><th>完整性摘要</th><th>下载</th></tr></thead><tbody>{[...outputs].reverse().map(item => <tr key={item.id}><td>{outputNames[item.family]}</td><td>v{item.version}</td><td>{item.current ? item.approved ? "当前 · 已批准" : "当前 · 待审核稿" : "历史 · 已过期"}</td><td><code title={item.sha256}>{item.sha256.slice(0, 12)}…</code></td><td><a href={item.family === "technical-solution" ? item.current ? artifactDownload(item.id) : artifactHistoryDownload(item.id) : item.current ? draftDownload(item.id) : draftHistoryDownload(item.id)}>{item.current ? "下载当前文件" : "下载历史文件"}</a></td></tr>)}</tbody></table></div> : <EmptyState title="暂无成果版本" detail="已保存的输入和蓝图记录仍可在下方追溯。"/>}</section>
      <section className="pd-panel"><h3>项目生成与审核记录</h3>{historyError ? <p role="alert">{historyError}</p> : !history ? <p role="status">正在读取版本链…</p> : <ol className="pd-timeline">{[...history.timeline].reverse().map(event => <li key={`${event.event}-${event.id}`}><span className="pd-timeline-dot"/><div><strong>{({ revision: "版本保存", external_upload: "资料上传", ai_task: "后台处理", artifact: "成果生成", approval: "人工审核" } as Record<string, string>)[event.event] || "项目记录"}{event.family ? ` · ${outputNames[event.family] || event.family}` : ""}{event.version ? ` v${event.version}` : ""}</strong><p>{event.reason || event.kind || "服务端已记录"} · {event.actor?.name || "系统"}</p>{event.sha256 && <small>摘要 {event.sha256.slice(0, 16)}…</small>}</div></li>)}</ol>}</section></>}
  </div>;
}

function BlockerNotes({ task }: { task: DocumentTask }) { const notes = Array.from(new Set(Object.values(task.blockers || {}).map(value => value.detail))); return notes.length ? <div className="pd-blockers">{notes.map(note => <p key={note}><ProductIcon name="shield"/>{note}</p>)}</div> : null; }

function BlueprintPanel({ task, disabled, busy, onAction }: { task: DocumentTask; disabled: (action: string) => boolean; busy: boolean; onAction: Action }) {
  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState<BlueprintPayload | null>(null);
  const [baseVersion, setBaseVersion] = useState(task.version);
  const [confirmed, setConfirmed] = useState(false);
  const [comment, setComment] = useState("");
  useUnsavedWarning(editing);
  useEffect(() => { setConfirmed(false); setComment(""); }, [task.blueprint?.id, task.blueprint?.sha256]);
  const blueprint = task.blueprint;
  const changed = editing && task.version !== baseVersion;
  function edit() {
    setDraft(blueprint ? structuredClone(blueprint.payload) : { purpose: task.input?.requirements || "", audience: "项目评审人员", chapters: [{ id: "chapter-1", title: "项目概述", scope: "", source_ids: [] }], conditions: (task.input?.conditions || []).map(text => ({ text, type: "human" as const })), missing: [], conflicts: [], template_version: "frozen-original-v1" });
    setBaseVersion(task.version); setEditing(true); setConfirmed(false);
  }
  const sourceChoices = [...task.sources.map(source => ({ id: source.id, name: source.original_name })), ...(task.input?.items || []).filter(item => item.row_id).map(item => ({ id: String(item.row_id), name: `清单行 ${item.row_id}：${item.name}` })),  ...(task.input?.knowledge_sources || []).map(source => ({ id: source.id, name: source.location }))];
  return <section className="pd-panel pd-blueprint"><div className="pd-panel-heading"><div><h3>项目蓝图 {blueprint && <span className="pd-badge info">v{blueprint.version}</span>}</h3><p className="pd-muted">确认目标、章节、资料缺口和实施条件后，再进入正文编制。</p></div>{!editing && <button className="button secondary" disabled={disabled("save_blueprint")} onClick={edit}>{blueprint ? "修改蓝图" : "人工编制蓝图"}</button>}</div>
    {editing && draft ? <form onSubmit={async event => { event.preventDefault(); if (!changed && await onAction("blueprint/", { payload: { ...draft, missing: lines(draft.missing.join("\n")), conflicts: lines(draft.conflicts.join("\n")) } })) setEditing(false); }}>
      {changed && <p role="alert" className="pd-feedback">服务端已出现新版本。当前编辑仍保留，请取消本地编辑并重新载入后核对，不能直接覆盖。</p>}
      <fieldset className="pd-form-fields" disabled={busy || changed || disabled("save_blueprint")}>
        <div className="pd-form-columns"><Field id="visual-blueprint-purpose" label="建设目标"><textarea id="visual-blueprint-purpose" required maxLength={5000} value={draft.purpose} onChange={event => setDraft({ ...draft, purpose: event.target.value })}/></Field><Field id="visual-blueprint-audience" label="文档受众"><input id="visual-blueprint-audience" required maxLength={1000} value={draft.audience} onChange={event => setDraft({ ...draft, audience: event.target.value })}/></Field></div>
        <h4>章节与建设范围</h4>{draft.chapters.map((chapter, index) => <div className="pd-blueprint-chapter" key={chapter.id}><span className="pd-number">{index + 1}</span><div><Field id={`visual-chapter-${index}`} label={`第 ${index + 1} 章标题`}><input id={`visual-chapter-${index}`} value={chapter.title} required maxLength={160} onChange={event => setDraft({ ...draft, chapters: draft.chapters.map((value, i) => i === index ? { ...value, title: event.target.value } : value) })}/></Field><Field id={`visual-scope-${index}`} label={`第 ${index + 1} 章范围`}><textarea id={`visual-scope-${index}`} value={chapter.scope} maxLength={5000} onChange={event => setDraft({ ...draft, chapters: draft.chapters.map((value, i) => i === index ? { ...value, scope: event.target.value } : value) })}/></Field><fieldset className="pd-source-choices"><legend>引用资料</legend>{sourceChoices.length ? sourceChoices.map(source => <label key={source.id}><input type="checkbox" checked={chapter.source_ids.includes(source.id)} onChange={event => setDraft({ ...draft, chapters: draft.chapters.map((value, i) => i === index ? { ...value, source_ids: event.target.checked ? [...value.source_ids, source.id] : value.source_ids.filter(id => id !== source.id) } : value) })}/>{source.name}</label>) : <small>尚无附件，可先整理章节范围。</small>}</fieldset></div><button className="text-button pd-danger" type="button" disabled={draft.chapters.length <= 1} aria-label={`移除第 ${index + 1} 章`} onClick={() => setDraft({ ...draft, chapters: draft.chapters.filter((_, i) => i !== index) })}>移除</button></div>)}<button className="button secondary" type="button" disabled={draft.chapters.length >= 200} onClick={() => setDraft({ ...draft, chapters: [...draft.chapters, { id: `chapter-${crypto.randomUUID()}`, title: "", scope: "", source_ids: [] }] })}>＋ 添加章节</button>
        <h4>实施与审核条件</h4>{draft.conditions.map((condition, index) => <div className="pd-condition-row" key={index}><input aria-label={`条件 ${index + 1}`} value={condition.text} required maxLength={1000} onChange={event => setDraft({ ...draft, conditions: draft.conditions.map((value, i) => i === index ? { ...value, text: event.target.value } : value) })}/><select aria-label={`条件 ${index + 1} 核对方式`} value={condition.type} onChange={event => setDraft({ ...draft, conditions: draft.conditions.map((value, i) => i === index ? { ...value, type: event.target.value as "human" | "program" | "model" } : value) })}><option value="human">人工核对</option><option value="program">程序校验</option><option value="model">模型辅助</option></select><button className="text-button" type="button" disabled={task.input?.conditions.includes(condition.text)} onClick={() => setDraft({ ...draft, conditions: draft.conditions.filter((_, i) => i !== index) })}>移除</button></div>)}<button className="text-button" type="button" onClick={() => setDraft({ ...draft, conditions: [...draft.conditions, { text: "", type: "human" }] })}>＋ 添加条件</button>
        <div className="pd-form-columns"><Field id="visual-missing" label="资料缺口（每行一项）"><textarea id="visual-missing" value={draft.missing.join("\n")} onChange={event => setDraft({ ...draft, missing: event.target.value.split("\n") })}/></Field><Field id="visual-conflicts" label="来源冲突（每行一项）"><textarea id="visual-conflicts" value={draft.conflicts.join("\n")} onChange={event => setDraft({ ...draft, conflicts: event.target.value.split("\n") })}/></Field></div>
      </fieldset><div className="pd-actions"><button type="submit" className="button primary" disabled={changed || disabled("save_blueprint")}>保存蓝图新版本</button><button type="button" className="button secondary" disabled={busy} onClick={() => { if (window.confirm("放弃当前未保存的蓝图编辑？")) setEditing(false); }}>取消编辑</button></div>
    </form> : blueprint ? <>
      <div className="pd-blueprint-summary"><h4>项目概述</h4><p>{blueprint.payload.purpose}</p><small>受众：{blueprint.payload.audience}</small></div><div className="pd-blueprint-columns"><section><h4>主要建设内容</h4><ol className="pd-blueprint-outline">{blueprint.payload.chapters.map((chapter, index) => <li key={chapter.id}><span className="pd-number">{index + 1}</span><div><strong>{chapter.title}</strong><p>{chapter.scope || "未单独说明范围"}</p><small>引用 {chapter.source_ids.length} 项资料</small></div></li>)}</ol></section><section><h4>实施与审核条件</h4>{blueprint.payload.conditions.length ? blueprint.payload.conditions.map((condition, index) => <p className="pd-condition" key={index}><ProductIcon name="shield"/>{condition.text}<small>{({ human: "人工核对", program: "程序校验", model: "模型辅助" })[condition.type]}</small></p>) : <p className="pd-muted">暂无条件记录</p>}</section></div>
      <div className="pd-issue-grid"><section><strong>{task.input?.items.length || 0}<small>清单事实行</small></strong><p>来自项目输入与上传清单</p></section><section><strong>{blueprint.payload.conditions.length}<small>待核对条件</small></strong><p>审批不会移除原始条件</p></section><section><strong>{blueprint.payload.missing.filter(Boolean).length + blueprint.payload.conflicts.filter(Boolean).length}<small>缺口与冲突</small></strong><p>{[...blueprint.payload.missing, ...blueprint.payload.conflicts].filter(Boolean).join("；") || "暂未记录，确认前请核对资料完整性"}</p></section></div>
      <div className="pd-blueprint-review"><Field id="visual-blueprint-comment" label="蓝图审核意见"><textarea id="visual-blueprint-comment" disabled={disabled("review_blueprint")} value={comment} onChange={event => setComment(event.target.value)} placeholder="说明确认依据，或需要修改的内容…" maxLength={10000}/></Field><label className="pd-confirm"><input type="checkbox" checked={confirmed} disabled={disabled("review_blueprint")} onChange={event => setConfirmed(event.target.checked)}/>我已核对本版本的目标、章节、条件、缺口与冲突。</label><div className="pd-form-footer"><span>审批绑定蓝图 v{blueprint.version} · 摘要 {blueprint.sha256.slice(0, 12)}</span><div className="pd-actions"><button className="button secondary" disabled={disabled("review_blueprint") || !comment.trim()} onClick={() => void onAction("decisions/", { target: "blueprint", target_id: blueprint.id, sha256: blueprint.sha256, decision: "revise", comment: comment.trim() })}>退回修改</button><button className="button primary" disabled={disabled("review_blueprint") || !confirmed || !comment.trim()} onClick={() => void onAction("decisions/", { target: "blueprint", target_id: blueprint.id, sha256: blueprint.sha256, decision: "approve", comment: comment.trim() })}>确认本版蓝图并继续<ProductIcon name="arrow"/></button></div></div>{disabled("review_blueprint") && <p className="pd-muted">仅指定的授权审核人可在待审核状态确认。创建者不能代为批准。</p>}</div>
    </> : <EmptyState title="等待形成项目蓝图" detail="可通过模型生成，也可由项目负责人先人工整理目标、章节与条件。模型授权不足不会阻止人工准备。"/>}
  </section>;
}
